// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Emu.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.AccessPolicies.AccessPolicy", b =>
                {
                    b.Property<Guid>("AccessPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_policy_id");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean")
                        .HasColumnName("can_read");

                    b.Property<bool>("CanWrite")
                        .HasColumnType("boolean")
                        .HasColumnName("can_write");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PathPrefix")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path_prefix");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccessPolicyId")
                        .HasName("pk_access_policy");

                    b.HasIndex("ApiKeyId")
                        .HasDatabaseName("IX_AccessPolicy_ApiKeyId");

                    b.HasIndex("EnvironmentId")
                        .HasDatabaseName("ix_access_policy_environment_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AccessPolicy_IsActive");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_access_policy_project_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_AccessPolicy_TenantId");

                    b.HasIndex("ApiKeyId", "PathPrefix")
                        .HasDatabaseName("IX_AccessPolicy_ApiKeyId_PathPrefix");

                    b.ToTable("AccessPolicy", (string)null);
                });

            modelBuilder.Entity("Domain.ApiKeys.ApiKey", b =>
                {
                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ApiKeyId")
                        .HasName("pk_api_key");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("IX_ApiKey_KeyHash");

                    b.HasIndex("KeyPrefix")
                        .HasDatabaseName("IX_ApiKey_KeyPrefix");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_ApiKey_TenantId");

                    b.ToTable("ApiKey", (string)null);
                });

            modelBuilder.Entity("Domain.AuditLogs.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_log_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<short>("ActorType")
                        .HasMaxLength(50)
                        .HasColumnType("smallint")
                        .HasColumnName("actor_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<short>("ResourceType")
                        .HasMaxLength(50)
                        .HasColumnType("smallint")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_agent");

                    b.HasKey("AuditLogId")
                        .HasName("pk_audit_log");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AuditLog_CreatedAt");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_AuditLog_TenantId");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("IX_AuditLog_ResourseType_ResourseId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_AuditLog_TenantId_CreatedAt");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("Domain.Environments.ProjectEnvironment", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EnvironmentId")
                        .HasName("pk_project_environment");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_ProjectEnvironment_ProjectId");

                    b.HasIndex("ProjectId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_ProjectEnvironment_ProjectId_Slug");

                    b.ToTable("ProjectEnvironment", (string)null);
                });

            modelBuilder.Entity("Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProjectId")
                        .HasName("pk_project");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Project_IsActive");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Project_TenantId");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Project_TenantId_Slug");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("Domain.Secrets.Secret", b =>
                {
                    b.Property<Guid>("SecretId")
                        .HasColumnType("uuid")
                        .HasColumnName("secret_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("current_version_number");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<short>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SecretId")
                        .HasName("pk_secret");

                    b.HasIndex("EnvironmentId")
                        .HasDatabaseName("IX_Secret_EnvironmentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Secret_Status");

                    b.HasIndex("EnvironmentId", "Path")
                        .IsUnique()
                        .HasDatabaseName("IX_Secret_EnvironmentId_Path");

                    b.ToTable("Secret", (string)null);
                });

            modelBuilder.Entity("Domain.Secrets.SecretVersion", b =>
                {
                    b.Property<Guid>("SecretVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("secret_version_id");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("algorithm");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_value");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nonce");

                    b.Property<Guid>("SecretId")
                        .HasColumnType("uuid")
                        .HasColumnName("secret_id");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tag");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("SecretVersionId")
                        .HasName("pk_secret_version");

                    b.HasIndex("SecretId")
                        .HasDatabaseName("IX_SecretVersion_SecretId");

                    b.HasIndex("SecretId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_SecretVersion_SecretId_VersionNumber");

                    b.ToTable("SecretVersion", (string)null);
                });

            modelBuilder.Entity("Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId")
                        .HasName("pk_tenant");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Tenant_IsActive");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Tenant_Slug");

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_user");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_tenant_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_tenant_id_email");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Domain.AccessPolicies.AccessPolicy", b =>
                {
                    b.HasOne("Domain.ApiKeys.ApiKey", "ApiKey")
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_policy_api_keys_api_key_id");

                    b.HasOne("Domain.Environments.ProjectEnvironment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_access_policy_project_environment_environment_id");

                    b.HasOne("Domain.Projects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_access_policy_projects_project_id");

                    b.HasOne("Domain.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_policy_tenants_tenant_id");

                    b.Navigation("ApiKey");

                    b.Navigation("Environment");

                    b.Navigation("Project");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.ApiKeys.ApiKey", b =>
                {
                    b.HasOne("Domain.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_api_key_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.AuditLogs.AuditLog", b =>
                {
                    b.HasOne("Domain.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Environments.ProjectEnvironment", b =>
                {
                    b.HasOne("Domain.Projects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_environment_project_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Projects.Project", b =>
                {
                    b.HasOne("Domain.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Secrets.Secret", b =>
                {
                    b.HasOne("Domain.Environments.ProjectEnvironment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_secret_project_environment_environment_id");

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("Domain.Secrets.SecretVersion", b =>
                {
                    b.HasOne("Domain.Secrets.Secret", "Secret")
                        .WithMany()
                        .HasForeignKey("SecretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_secret_version_secret_secret_id");

                    b.Navigation("Secret");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.HasOne("Domain.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tenant_tenant_id");

                    b.Navigation("Tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
